/**
 * Build the stellar background layer from the HYG star catalogue.
 *
 * Source: https://github.com/astronexus/HYG-Database  (hygdata_v41.csv)
 * Licence: CC BY-SA 4.0 (see the repository for the full attribution).
 *
 * The catalogue is combined with Hipparcos/Yale/Gliese data and gives, for every
 * star, right ascension, declination, apparent magnitude and B-V colour index.
 * Only stars brighter than the configured limiting magnitude are exported, which
 * is what the naked eye can see and what keeps the payload small.
 *
 * Output
 *   public/data/stars/stars.bin     Float32Array, 4 values per star: raRad, decRad, mag, colorIndex
 *   public/data/stars/stars.json    manifest + named stars used for annotation
 *
 * Usage:  NODE_USE_ENV_PROXY=1 node scripts/update-stars.mjs
 */
import { createReadStream } from 'node:fs'
import path from 'node:path'
import { unlink, writeFile } from 'node:fs/promises'
import readline from 'node:readline'
import { PUBLIC_DATA_DIR, ensureDir, httpText, log, writeBuffer, writeJson, writeText } from './lib/io.mjs'

const HYG_URL = 'https://raw.githubusercontent.com/astronexus/HYG-Database/main/hyg/CURRENT/hygdata_v41.csv'
const LIMITING_MAGNITUDE = 7.0
const MAX_NAMED_STARS = 400

const RA_HOURS_TO_RAD = (Math.PI / 12)
const DEG_TO_RAD = (Math.PI / 180)

/** Minimal RFC 4180 field splitter; the HYG export quotes every column. */
function parseCsvLine(line) {
  const fields = []
  let current = ''
  let inQuotes = false
  for (let index = 0; index < line.length; index++) {
    const character = line[index]
    if (inQuotes) {
      if (character === '"') {
        if (line[index + 1] === '"') {
          current += '"'
          index++
        } else {
          inQuotes = false
        }
      } else {
        current += character
      }
    } else if (character === '"') {
      inQuotes = true
    } else if (character === ',') {
      fields.push(current)
      current = ''
    } else {
      current += character
    }
  }
  fields.push(current)
  return fields
}

async function main() {
  const dir = path.join(PUBLIC_DATA_DIR, 'stars')
  await ensureDir(dir)
  log(`Downloading HYG catalogue (${HYG_URL}) ...`)
  const csv = await httpText(HYG_URL, { timeoutMs: 180_000 })

  const tempFile = path.join(dir, '.hyg.csv')
  await writeText(tempFile, csv)

  const reader = readline.createInterface({ input: createReadStream(tempFile), crlfDelay: Infinity })
  const header = []
  const values = []
  const named = []
  let total = 0

  for await (const line of reader) {
    if (header.length === 0) {
      header.push(...parseCsvLine(line))
      continue
    }
    if (line.trim() === '') continue
    total++
    const fields = parseCsvLine(line)
    const record = Object.fromEntries(header.map((name, index) => [name, fields[index]]))
    // HYG row 0 is the Sun itself, which is a solar-system body, not a background star.
    if (record.id === '0') continue
    const mag = Number(record.mag)
    const ra = Number(record.ra)
    const dec = Number(record.dec)
    if (!Number.isFinite(mag) || !Number.isFinite(ra) || !Number.isFinite(dec)) continue
    if (mag > LIMITING_MAGNITUDE) continue
    const colorIndex = Number(record.ci)
    values.push(ra * RA_HOURS_TO_RAD, dec * DEG_TO_RAD, mag, Number.isFinite(colorIndex) ? colorIndex : 0.65)
    const proper = (record.proper ?? '').trim()
    if (proper) {
      named.push({
        name: proper,
        bayer: (record.bayer ?? '').trim() || null,
        constellation: (record.con ?? '').trim() || null,
        raRad: ra * RA_HOURS_TO_RAD,
        decRad: dec * DEG_TO_RAD,
        magnitude: mag,
        colorIndex: Number.isFinite(colorIndex) ? colorIndex : 0.65,
        distanceParsec: Number.isFinite(Number(record.dist)) ? Number(record.dist) : null,
        spectralType: (record.spect ?? '').trim() || null,
      })
    }
  }
  await reader.close()

  const array = new Float32Array(values)
  const buffer = Buffer.from(array.buffer, array.byteOffset, array.byteLength)
  await writeBuffer(path.join(dir, 'stars.bin'), buffer)

  named.sort((a, b) => a.magnitude - b.magnitude)

  await writeJson(path.join(dir, 'stars.json'), {
    $comment:
      'Generated by scripts/update-stars.mjs from the HYG v4.1 catalogue (astronexus/HYG-Database, CC BY-SA 4.0). stars.bin is a little-endian Float32Array with four values per star: right ascension (rad, J2000), declination (rad, J2000), apparent visual magnitude, B-V colour index.',
    source: HYG_URL,
    license: 'CC BY-SA 4.0',
    retrievedAt: new Date().toISOString(),
    limitingMagnitude: LIMITING_MAGNITUDE,
    counts: { scanned: total, exported: array.length / 4, named: named.length },
    binary: { file: 'stars.bin', stride: 4, layout: ['raRad', 'decRad', 'magnitude', 'colorIndex'] },
    namedStars: named.slice(0, MAX_NAMED_STARS).map(({ name, bayer, constellation, magnitude, raRad, decRad, colorIndex, spectralType, distanceParsec }) => ({
      name, bayer, constellation, magnitude, raRad, decRad, colorIndex, spectralType, distanceParsec,
    })),
  })

  await unlink(tempFile)
  log(`Exported ${array.length / 4} stars (${(buffer.byteLength / 1024).toFixed(0)} KB), ${named.length} named.`)
}

main().catch((error) => {
  process.stderr.write(`${String(error?.stack ?? error)}\n`)
  process.exit(1)
})